const DISEASE_SUFFIX =
  /\s*'?s?\s*(disease|syndrome|palsy|sign|chorea|anemia|lymphoma|sarcoma|tetralogy|contracture|deformity|phenomenon|arteritis|granulomatosis)/i;

const ALWAYS_KEEP = new Set([
  "parkinson",
  "parkinson's",
  "huntington",
  "huntington's",
  "crohn",
  "crohn's",
  "alzheimer",
  "alzheimer's",
  "addison",
  "addison's",
  "graves",
  "grave's",
  "cushing",
  "cushing's",
  "hodgkin",
  "hodgkin's",
  "non-hodgkin",
  "whipple",
  "whipple's",
  "kawasaki",
  "raynaud",
  "raynaud's",
  "kaposi",
  "kaposi's",
  "hashimoto",
  "hashimoto's",
  "sjogren",
  "sjögren",
  "sjogren's",
  "meniere",
  "meniere's",
  "dupuytren",
  "peyronie",
  "peyronie's",
  "barrett",
  "barrett's",
  "sheehan",
  "sheehan's",
  "dressler",
  "dressler's",
  "marfan",
  "ehlers",
  "danlos",
  "ebstein",
  "fallot",
  "guillain",
  "barre",
  "charcot",
  "osgood",
  "schlatter",
  "buerger",
  "wegener",
  "mallory",
  "weiss",
  "libman",
  "sacks",
  "rendu",
  "coxsackie",
  "legionella",
  "listeria",
  "klebsiella",
  "salmonella",
  "shigella",
  "giardia",
  "candida",
  "aspergillus",
  "mucor",
  "bartonella",
  "borrelia",
  "brucella",
  "chlamydia",
  "clostridium",
  "metformin",
  "lisinopril",
  "mesalamine",
  "atorvastatin",
  "levothyroxine",
  "amlodipine",
  "omeprazole",
  "losartan",
  "gabapentin",
  "sertraline",
  "insulin",
  "warfarin",
  "apixaban",
  "hba1c",
  "hemoglobin",
  "creatinine",
  "glucose",
  "cholesterol",
  "triglycerides",
  "tsh",
  "egfr",
  "ldl",
  "hdl",
  "wbc",
  "rbc",
  "inr",
  "ptt",
  "bnp",
  "troponin",
  "crp",
  "esr",
  "psa",
  "a1c",
]);

const CONTEXT_ONLY = new Set([
  "wilson",
  "wilson's",
  "bell",
  "bell's",
  "still",
  "still's",
  "wells",
  "conn",
  "conn's",
  "paget",
  "paget's",
  "barr",
  "epstein",
  "osler",
  "weber",
]);

export function isFrozenClinicalTerm(
  spanText: string,
  fullText: string,
  _start: number,
  end: number,
): boolean {
  const trimmed = spanText.trim().toLowerCase().replace(/[.,;:]+$/, "");
  if (!trimmed) return false;
  if (ALWAYS_KEEP.has(trimmed)) return true;
  const after = fullText.slice(end, end + 24);
  if (CONTEXT_ONLY.has(trimmed) && (DISEASE_SUFFIX.test(after) || /^['’]s\b/i.test(after))) {
    return true;
  }
  return false;
}
